from pathlib import Path
p=Path('index.html')
s=p.read_text()
if 'function startBoss()' in s:
    raise SystemExit('Boss already installed')
s=s.replace('🔫 Blaster von Anfang an · unendliche Munition · 💥 oder F feuern.<br>Gelbe Linien warnen vor tödlichen Lasern.','🔫 Blaster von Anfang an · unendliche Munition · 💥 oder F feuern.<br>☠️ Alle 30 Sekunden stoppt die Welt: Besiege den Boss, damit es weitergeht.<br>Gelbe Linien warnen vor tödlichen Lasern.')
s=s.replace("let W=0,H=0,G=0,dpr=1,running=false,last=performance.now(),t=0,score=0,clock=0,speed=330,spawn=1,pickClock=1.4,objects=[],pickups=[],shots=[],laser=null,particles=[],high=+(localStorage.brainFeastHigh||0),audio=true,ac=null,target=null;","let W=0,H=0,G=0,dpr=1,running=false,last=performance.now(),t=0,worldX=0,bossClock=0,bossCount=0,score=0,clock=0,speed=330,spawn=1,pickClock=1.4,objects=[],pickups=[],shots=[],bossShots=[],laser=null,boss=null,particles=[],high=+(localStorage.brainFeastHigh||0),audio=true,ac=null,target=null;")
s=s.replace("function reset(){t=score=clock=0;speed=330;spawn=.7;pickClock=1.2;objects=[];pickups=[];shots=[];laser=null;particles=[];target=null;Object.assign(p,{x:Math.min(120,W*.18),y:G-70,w:58,h:70,vx:0,vy:0,on:true,duck:false,lives:3,inv:0,hold:0,weapon:'blaster',ammo:Infinity,cool:0});hud()}","function reset(){t=worldX=bossClock=bossCount=score=clock=0;speed=330;spawn=.7;pickClock=1.2;objects=[];pickups=[];shots=[];bossShots=[];laser=null;boss=null;particles=[];target=null;Object.assign(p,{x:Math.min(120,W*.18),y:G-70,w:58,h:70,vx:0,vy:0,on:true,duck:false,lives:3,inv:0,hold:0,weapon:'blaster',ammo:Infinity,cool:0});hud()}")
anchor="function destroyObstacle(o,s){if(o.destroyed||o.type==='platform')return;o.destroyed=true;score+=o.type==='human'?180:120;burst(o.x+o.w/2,o.y+o.h/2);for(let i=0;i<9;i++)particles.push({x:o.x+o.w/2,y:o.y+o.h/2,vx:(Math.random()-.5)*360,vy:(Math.random()-.8)*300,l:.55,metal:o.type!=='human'});tone(s.type==='plasma'?210:150,.1,'sawtooth',.035);hud()}\n"
boss="""function startBoss(){bossCount++;let max=10+Math.floor(Math.random()*41),w=Math.min(150,Math.max(100,W*.18)),h=w*1.18;boss={x:W-w-24,y:G-h,w,h,hp:max,max,phase:0,shot:1.05,flash:0};objects=[];pickups=[];laser=null;shots=[];bossShots=[];target=null;hint.textContent='☠️ BOSS! '+max+' Treffer · Welt angehalten';hint.style.opacity='1';tone(90,.45,'sawtooth',.05)}
function beatBoss(){let bx=boss.x+boss.w/2,by=boss.y+boss.h/2;score+=1000+bossCount*250;for(let i=0;i<5;i++)burst(bx+(Math.random()-.5)*boss.w,by+(Math.random()-.5)*boss.h);tone(720,.28,'square',.04);boss=null;bossShots=[];bossClock=0;hint.textContent='Boss besiegt! Das Spiel läuft weiter.';hint.style.opacity='1';setTimeout(()=>hint.style.opacity='.15',2200);hud()}
function hitBoss(s){if(!boss||s.life<=0)return false;let hb={x:boss.x+12,y:boss.y+8,w:boss.w-24,h:boss.h-10},sb={x:s.x-s.r,y:s.y-s.r,w:s.r*2,h:s.r*2};if(!hit(sb,hb))return false;boss.hp--;boss.flash=.12;s.life=0;score+=25;burst(s.x,s.y);tone(190,.05,'square',.025);if(boss.hp<=0)beatBoss();return true}
function bossAttack(){if(!boss)return;let sx=boss.x+8,sy=boss.y+boss.h*.42,tx=p.x+p.w/2,ty=p.y+p.h/2,dx=tx-sx,dy=ty-sy,len=Math.hypot(dx,dy)||1,spd=360+bossCount*18;bossShots.push({x:sx,y:sy,vx:dx/len*spd,vy:dy/len*spd,r:9,life:4});tone(135,.09,'sawtooth',.03)}
"""
s=s.replace(anchor,anchor+boss)
a=s.index('function update(dt){');b=s.index('function rr(',a)
upd="""function update(dt){if(!running)return;t+=dt;p.inv=Math.max(0,p.inv-dt);p.cool=Math.max(0,p.cool-dt);if(key.shoot)fire();p.duck=key.down&&p.on;let accel=1350,max=330,dir=(key.right?1:0)-(key.left?1:0);if(target){target.life-=dt;let dx=target.x-(p.x+p.w/2);if(Math.abs(dx)>18)dir=Math.sign(dx);else target=null;if(target&&target.life<=0)target=null}p.vx+=dir*accel*dt;p.vx*=Math.pow(dir ? .32 : .02,dt);p.vx=Math.max(-max,Math.min(max,p.vx));p.x+=p.vx*dt;p.x=Math.max(4,Math.min(W-p.w-4,p.x));if(!p.on){p.hold+=dt;if(key.up&&p.hold<.38&&p.vy<0)p.vy-=Math.max(1700,H*2.15)*dt;p.vy+=2100*dt;let oldBottom=p.y+p.h;p.y+=p.vy*dt;let landing=G;if(!boss)for(let o of objects)if(o.safe&&p.vy>=0&&p.x+p.w*.75>o.x&&p.x+p.w*.25<o.x+o.w&&oldBottom<=o.y+8&&p.y+p.h>=o.y)landing=Math.min(landing,o.y);if(p.y+p.h>=landing){p.y=landing-p.h;p.vy=0;p.on=true}}else{let surface=G;if(!boss)for(let o of objects)if(o.safe&&p.x+p.w*.7>o.x&&p.x+p.w*.3<o.x+o.w&&Math.abs(p.y+p.h-o.y)<10)surface=Math.min(surface,o.y);p.y=surface-p.h}
if(!boss){bossClock+=dt;speed=Math.min(780,330+worldX*.027);worldX+=speed*dt;clock+=dt;while(clock>=.5){clock-=.5;score+=10;hud()}if(bossClock>=30)startBoss();if(!boss){spawn-=dt;if(spawn<=0){obstacle();spawn=.75+Math.random()*.55}pickClock-=dt;if(pickClock<=0){pickup();pickClock=1.4+Math.random()*1.8}if(!laser&&worldX>2500&&Math.random()<dt*.085)makeLaser();if(laser){laser.age+=dt;laser.state=laser.age<.65?'warn':laser.age<1.18?'active':'off';if(laser.age>1.55)laser=null}for(let o of objects){o.x-=speed*dt;o.phase+=dt*5}for(let q of pickups){q.x-=speed*dt;q.phase+=dt*4}}}
else{boss.phase+=dt;boss.flash=Math.max(0,boss.flash-dt);boss.shot-=dt;if(boss.shot<=0){bossAttack();boss.shot=Math.max(.52,1.18-bossCount*.055)+Math.random()*.32}boss.y=G-boss.h+Math.sin(boss.phase*2.2)*18}
for(let q of shots){q.x+=q.vx*dt;q.life-=dt}for(let q of bossShots){q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt}for(let q of shots){if(q.life<=0)continue;if(boss&&hitBoss(q))continue;for(let o of objects){if(o.destroyed||o.type==='platform')continue;if(hit({x:q.x-q.r,y:q.y-q.r,w:q.r*2,h:q.r*2},box(o))){destroyObstacle(o,q);q.pierce--;if(q.pierce<=0){q.life=0;break}}}}objects=objects.filter(o=>!o.destroyed&&o.x+o.w>-100);pickups=pickups.filter(q=>q.x>-50&&!q.got);shots=shots.filter(q=>q.life>0&&q.x<W+80);bossShots=bossShots.filter(q=>q.life>0&&q.x>-40&&q.x<W+40&&q.y>-40&&q.y<H+40);
let ph=p.duck?{x:p.x+10,y:p.y+p.h*.48,w:p.w-20,h:p.h*.52}:{x:p.x+9,y:p.y+7,w:p.w-18,h:p.h-8};if(!boss){for(let o of objects){if(o.safe&&p.vy>=0&&ph.y+ph.h<=o.y+12)continue;if(o.type==='platform')continue;let hb=box(o);if(o.type==='spikes')hb={x:o.x+4,y:o.y+10,w:o.w-8,h:o.h-10};if(o.type==='saw')hb={x:o.x+6,y:o.y+6,w:o.w-12,h:o.h-12};if(hit(ph,hb))hurt()}if(laser&&laser.state==='active'&&ph.y<laser.y+laser.thick/2&&ph.y+ph.h>laser.y-laser.thick/2)hurt();for(let q of pickups){if(Math.hypot(p.x+p.w/2-q.x,p.y+p.h/2-q.y)<45){q.got=true;if(q.type==='heart')p.lives=Math.min(3,p.lives+1);else score+=q.type==='gold'?500:100;hud();tone(q.type==='gold'?980:700,.08)}}}else{let bh={x:boss.x+15,y:boss.y+10,w:boss.w-30,h:boss.h-10};if(hit(ph,bh))hurt();for(let q of bossShots){if(hit(ph,{x:q.x-q.r,y:q.y-q.r,w:q.r*2,h:q.r*2})){q.life=0;hurt()}}}
for(let z of particles){z.l-=dt;z.vy+=500*dt;z.x+=z.vx*dt;z.y+=z.vy*dt}particles=particles.filter(z=>z.l>0)}
"""
s=s[:a]+upd+s[b:]
s=s.replace('(i*170-(t*speed*.1)%170)-60','(i*170-(worldX*.1)%170)-60').replace('for(let a=-(t*speed)%110;a<W;a+=110)','for(let a=-(worldX)%110;a<W;a+=110)')
s=s.replace('for(let o of objects)drawObj(o);for(let q of pickups)drawPick(q);for(let s of shots)drawShot(s);if(laser)drawLaser();drawPlayer();for(let z of particles)','for(let o of objects)drawObj(o);for(let q of pickups)drawPick(q);for(let s of shots)drawShot(s);for(let b of bossShots)drawBossShot(b);if(laser)drawLaser();if(boss)drawBoss();drawPlayer();for(let z of particles)')
draw="""function drawBossShot(b){x.save();x.translate(b.x,b.y);x.globalCompositeOperation='lighter';x.shadowColor='#ff174d';x.shadowBlur=22;x.fillStyle='#fff0f3';x.beginPath();x.arc(0,0,b.r,0,7);x.fill();x.fillStyle='#e0003c';x.beginPath();x.arc(0,0,b.r*.55,0,7);x.fill();x.restore()}
function drawBoss(){let b=boss,pulse=1+Math.sin(b.phase*5)*.035;x.save();x.translate(b.x+b.w/2,b.y+b.h/2);x.scale(pulse,pulse);x.shadowColor=b.flash?'#fff':'#ff174d';x.shadowBlur=b.flash?40:24;x.fillStyle=b.flash?'#fff':'#6f1735';x.beginPath();x.ellipse(0,5,b.w*.46,b.h*.45,0,0,7);x.fill();x.shadowBlur=0;x.fillStyle='#3a0a1c';for(let i=0;i<6;i++){let a=-2.55+i*.48;x.beginPath();x.moveTo(Math.cos(a)*b.w*.28,Math.sin(a)*b.h*.33);x.lineTo(Math.cos(a)*b.w*.58,Math.sin(a)*b.h*.58);x.lineTo(Math.cos(a+.16)*b.w*.32,Math.sin(a+.16)*b.h*.34);x.fill()}x.fillStyle='#f4e8de';x.beginPath();x.ellipse(-b.w*.16,-b.h*.12,b.w*.1,b.h*.12,0,0,7);x.ellipse(b.w*.16,-b.h*.12,b.w*.1,b.h*.12,0,0,7);x.fill();x.fillStyle='#ff174d';x.beginPath();x.arc(-b.w*.14,-b.h*.1,b.w*.035,0,7);x.arc(b.w*.18,-b.h*.1,b.w*.035,0,7);x.fill();x.fillStyle='#19050d';x.beginPath();x.ellipse(0,b.h*.12,b.w*.25,b.h*.15,0,0,7);x.fill();x.fillStyle='#fff';for(let i=-3;i<=3;i++){x.beginPath();x.moveTo(i*b.w*.055-b.w*.025,b.h*.02);x.lineTo(i*b.w*.055,b.h*.16);x.lineTo(i*b.w*.055+b.w*.025,b.h*.02);x.fill()}x.restore();let bw=Math.min(W*.72,560),bh=18,bx=(W-bw)/2,by=Math.max(66,H*.11);x.fillStyle='#180811';x.fillRect(bx-4,by-4,bw+8,bh+8);x.fillStyle='#5e102a';x.fillRect(bx,by,bw,bh);x.fillStyle='#ff315f';x.fillRect(bx,by,bw*(b.hp/b.max),bh);x.strokeStyle='#fff4';x.strokeRect(bx,by,bw,bh);x.fillStyle='#fff';x.font='1000 '+Math.max(14,H*.025)+'px system-ui';x.textAlign='center';x.fillText('☠️ END BOSS '+b.hp+' / '+b.max,W/2,by-10)}
"""
s=s.replace('function drawShot(s){',draw+'function drawShot(s){')
p.write_text(s)
