from pathlib import Path

path = Path("index.html")
s = path.read_text(encoding="utf-8")
if 'id="weapon"' in s:
    print("Weapons already installed")
    raise SystemExit(0)

def rep(old, new):
    global s
    if old not in s:
        raise RuntimeError("Expected source not found: " + old[:100])
    s = s.replace(old, new)

rep(".hud{position:absolute;top:max(10px,env(safe-area-inset-top));left:10px;right:10px;display:flex;justify-content:space-between;gap:8px;pointer-events:none;", ".hud{position:absolute;top:max(10px,env(safe-area-inset-top));left:10px;right:10px;display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap;pointer-events:none;")
rep("#sound{pointer-events:auto;border:0;color:#fff;min-width:44px}", "#sound{pointer-events:auto;border:0;color:#fff;min-width:44px}#weapon{color:#ffd24a}")
rep("@media (pointer:fine){", "@media(max-width:370px){.ctrl{width:52px;height:52px;font-size:24px}.cluster{gap:6px}.pill{padding:6px 9px;font-size:11px}}@media (pointer:fine){")
rep('<div class="hud"><span class="pill" id="score">Punkte 0</span><span class="pill" id="lives">❤️❤️❤️</span><button class="pill" id="sound">🔊</button></div>', '<div class="hud"><span class="pill" id="score">Punkte 0</span><span class="pill" id="weapon">🔫 Keine Waffe</span><span class="pill" id="lives">❤️❤️❤️</span><button class="pill" id="sound">🔊</button></div>')
rep('<div class="hint" id="hint">Tippe ins Spielfeld oder nutze die Tasten</div>', '<div class="hint" id="hint">Waffe einsammeln · 💥 feuern · F auf Tastatur</div>')
rep('<div class="cluster"><button class="ctrl" data-key="down">▼</button><button class="ctrl" data-key="up">▲</button></div>', '<div class="cluster"><button class="ctrl" data-key="shoot">💥</button><button class="ctrl" data-key="down">▼</button><button class="ctrl" data-key="up">▲</button></div>')
rep('◀ ▶ bewegen · ▲ kurz = kleiner Sprung · ▲ halten = hoher Sprung · ▼ ducken<br>Gelbe Linien warnen vor tödlichen Lasern.', '◀ ▶ bewegen · ▲ kurz = kleiner Sprung · ▲ halten = hoher Sprung · ▼ ducken<br>🔫 Waffen einsammeln · 💥 oder F feuern · Schüsse zerstören Hindernisse.<br>Gelbe Linien warnen vor tödlichen Lasern.')
rep("const start=$('start'),over=$('over'),scoreEl=$('score'),livesEl=$('lives'),soundBtn=$('sound'),hint=$('hint');", "const start=$('start'),over=$('over'),scoreEl=$('score'),weaponEl=$('weapon'),livesEl=$('lives'),soundBtn=$('sound'),hint=$('hint');")
rep("objects=[],pickups=[],laser=null,particles=[]", "objects=[],pickups=[],shots=[],laser=null,particles=[]")
rep("const key={left:false,right:false,up:false,down:false};", "const key={left:false,right:false,up:false,down:false,shoot:false};")
rep("const p={x:120,y:0,w:58,h:70,vx:0,vy:0,on:true,duck:false,lives:3,inv:0,hold:0};", "const p={x:120,y:0,w:58,h:70,vx:0,vy:0,on:true,duck:false,lives:3,inv:0,hold:0,weapon:null,ammo:0,cool:0};")
rep("objects=[];pickups=[];laser=null;particles=[];target=null;Object.assign(p,{x:Math.min(120,W*.18),y:G-70,w:58,h:70,vx:0,vy:0,on:true,duck:false,lives:3,inv:0,hold:0});hud()", "objects=[];pickups=[];shots=[];laser=null;particles=[];target=null;Object.assign(p,{x:Math.min(120,W*.18),y:G-70,w:58,h:70,vx:0,vy:0,on:true,duck:false,lives:3,inv:0,hold:0,weapon:null,ammo:0,cool:0});hud()")
rep("function hud(){scoreEl.textContent='Punkte '+Math.floor(score).toLocaleString('de-DE');livesEl.textContent='❤️'.repeat(Math.max(0,p.lives))+'☠️'.repeat(Math.max(0,3-p.lives))}", "function hud(){scoreEl.textContent='Punkte '+Math.floor(score).toLocaleString('de-DE');weaponEl.textContent=p.weapon?(p.weapon==='plasma'?'⚡ Plasma ':'🔫 Blaster ')+p.ammo:'🔫 Keine Waffe';livesEl.textContent='❤️'.repeat(Math.max(0,p.lives))+'☠️'.repeat(Math.max(0,3-p.lives))}")
rep("function control(name,v){key[name]=v;document.querySelector(`[data-key=\"${name}\"]`)?.classList.toggle('active',v);if(name==='up'){if(v)jump();else if(p.vy<-180)p.vy*=.48}}", "function control(name,v){key[name]=v;document.querySelector(`[data-key=\"${name}\"]`)?.classList.toggle('active',v);if(name==='up'){if(v)jump();else if(p.vy<-180)p.vy*=.48}if(name==='shoot'&&v)fire()}")
rep("b.setPointerCapture?.(e.pointerId);", "try{b.setPointerCapture?.(e.pointerId)}catch(_){ }")
rep("let m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down',Space:'up'}[e.code]", "let m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down',Space:'up',KeyF:'shoot',KeyX:'shoot'}[e.code]")
rep("function pickup(){let type=Math.random()<.12?'heart':Math.random()<.22?'gold':'brain';pickups.push({type,x:W+50,y:G-(70+Math.random()*180),r:18,phase:Math.random()*6})}", "function pickup(){let r=Math.random(),type=r<.1?'heart':r<.26?'weapon':r<.38?'gold':'brain';pickups.push({type,weapon:type==='weapon'?(Math.random()<.72?'blaster':'plasma'):null,x:W+50,y:G-(70+Math.random()*180),r:18,phase:Math.random()*6})}")
rep("function burst(px,py){for(let i=0;i<18;i++)particles.push({x:px,y:py,vx:(Math.random()-.5)*260,vy:(Math.random()-.8)*240,l:.7})}", "function burst(px,py){for(let i=0;i<18;i++)particles.push({x:px,y:py,vx:(Math.random()-.5)*260,vy:(Math.random()-.8)*240,l:.7})}\nfunction fire(){if(!running||!p.weapon||p.ammo<=0||p.cool>0)return;let plasma=p.weapon==='plasma',sy=p.y+(p.duck?p.h*.68:p.h*.43);shots.push({x:p.x+p.w-2,y:sy,vx:plasma?920:1050,r:plasma?8:5,life:1.55,pierce:plasma?3:1,type:p.weapon});p.ammo--;p.cool=plasma?.28:.16;particles.push({x:p.x+p.w,y:sy,vx:80,vy:0,l:.18,shot:true});tone(plasma?760:1020,.06,plasma?'sawtooth':'square',.025);if(p.ammo<=0)p.weapon=null;hud()}\nfunction destroyObstacle(o,s){if(o.destroyed||o.type==='platform')return;o.destroyed=true;score+=o.type==='human'?180:120;burst(o.x+o.w/2,o.y+o.h/2);for(let i=0;i<9;i++)particles.push({x:o.x+o.w/2,y:o.y+o.h/2,vx:(Math.random()-.5)*360,vy:(Math.random()-.8)*300,l:.55,metal:o.type!=='human'});tone(s.type==='plasma'?210:150,.1,'sawtooth',.035);hud()}")
rep("p.inv=Math.max(0,p.inv-dt);p.duck=key.down&&p.on;", "p.inv=Math.max(0,p.inv-dt);p.cool=Math.max(0,p.cool-dt);if(key.shoot)fire();p.duck=key.down&&p.on;")
rep("for(let o of objects){o.x-=speed*dt;o.phase+=dt*5}for(let q of pickups){q.x-=speed*dt;q.phase+=dt*4}objects=objects.filter(o=>o.x+o.w>-100);pickups=pickups.filter(q=>q.x>-50&&!q.got);", "for(let o of objects){o.x-=speed*dt;o.phase+=dt*5}for(let q of pickups){q.x-=speed*dt;q.phase+=dt*4}for(let s of shots){s.x+=s.vx*dt;s.life-=dt}for(let s of shots){if(s.life<=0)continue;for(let o of objects){if(o.destroyed||o.type==='platform')continue;if(hit({x:s.x-s.r,y:s.y-s.r,w:s.r*2,h:s.r*2},box(o))){destroyObstacle(o,s);s.pierce--;if(s.pierce<=0){s.life=0;break}}}}objects=objects.filter(o=>!o.destroyed&&o.x+o.w>-100);pickups=pickups.filter(q=>q.x>-50&&!q.got);shots=shots.filter(s=>s.life>0&&s.x<W+80);")
rep("if(q.type==='heart')p.lives=Math.min(3,p.lives+1);else score+=q.type==='gold'?500:100;hud();tone(q.type==='gold'?980:700,.08)", "if(q.type==='heart')p.lives=Math.min(3,p.lives+1);else if(q.type==='weapon'){let same=p.weapon===q.weapon,add=q.weapon==='plasma'?5:10;p.weapon=q.weapon;p.ammo=same?p.ammo+add:add;tone(q.weapon==='plasma'?880:620,.14,'square',.035)}else score+=q.type==='gold'?500:100;hud();if(q.type!=='weapon')tone(q.type==='gold'?980:700,.08)")
rep("for(let o of objects)drawObj(o);for(let q of pickups)drawPick(q);if(laser)drawLaser();drawPlayer();", "for(let o of objects)drawObj(o);for(let q of pickups)drawPick(q);for(let s of shots)drawShot(s);if(laser)drawLaser();drawPlayer();")
rep("function drawPick(q){x.save();x.translate(q.x,q.y+Math.sin(q.phase)*5);x.shadowColor=q.type==='gold'?'#ffcd45':'#ff4873';x.shadowBlur=12;x.fillStyle=q.type==='gold'?'#f1b722':q.type==='heart'?'#da1748':'#d97891';if(q.type==='heart'){", "function drawPick(q){x.save();x.translate(q.x,q.y+Math.sin(q.phase)*5);x.shadowColor=q.type==='weapon'?'#56ddff':q.type==='gold'?'#ffcd45':'#ff4873';x.shadowBlur=12;x.fillStyle=q.type==='weapon'?'#5be1ff':q.type==='gold'?'#f1b722':q.type==='heart'?'#da1748':'#d97891';if(q.type==='weapon'){x.save();x.rotate(-.18);rr(-20,-8,31,14,5);x.fill();x.fillStyle=q.weapon==='plasma'?'#b36cff':'#eefcff';x.fillRect(6,-4,18,6);x.fillStyle='#39404a';rr(-6,4,9,16,3);x.fill();x.restore()}else if(q.type==='heart'){")
rep("function drawPlayer(){", "function drawShot(s){x.save();x.translate(s.x,s.y);x.globalCompositeOperation='lighter';x.shadowColor=s.type==='plasma'?'#b84dff':'#ffcf55';x.shadowBlur=s.type==='plasma'?22:14;x.fillStyle=s.type==='plasma'?'#f0c7ff':'#fff4b0';x.beginPath();x.ellipse(0,0,s.r*2.2,s.r,0,0,7);x.fill();x.restore()}\nfunction drawPlayer(){")
rep("x.fillStyle='#fff';for(let i=-2;i<=2;i++){x.beginPath();x.moveTo(i*6-3,h*.04);x.lineTo(i*6,h*.17);x.lineTo(i*6+3,h*.04);x.fill()}x.restore()}", "x.fillStyle='#fff';for(let i=-2;i<=2;i++){x.beginPath();x.moveTo(i*6-3,h*.04);x.lineTo(i*6,h*.17);x.lineTo(i*6+3,h*.04);x.fill()}if(p.weapon){x.fillStyle=p.weapon==='plasma'?'#8d38d6':'#3d4652';rr(19,-2,28,10,4);x.fill();x.fillStyle='#dff8ff';x.fillRect(41,0,10,4)}x.restore()}")

path.write_text(s, encoding="utf-8")
print("Weapons installed")
